import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AddSense from "@/components/GoogleAds/AddSense";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Expense Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{process.env.NODE_ENV === "production" && <AddSense />}</head>
      <body className={`${inter.variable}`}>{children}</body>
    </html>
  );
}
